export const exerciseTypes = [
  "Standard Push-ups",
  "Wide-Grip Push-ups",
  "Diamond Push-ups",
  "Decline Push-ups",
  "Incline Push-ups",
  "One-Arm Push-ups",
  "Standard Pull-ups",
  "Chin-ups",
  "Wide-Grip Pull-ups",
  "Close-Grip Pull-ups",
  "Commando Pull-ups",
  "Bench Dips",
  "Tricep Dips",
  "Chest Dips",
  "Pike Push-ups",
  "Handstand Push-ups",
  "Tricep Extensions",
  "Standard Plank",
  "Side Plank",
  "Reverse Plank",
  "Plank with Leg Lift",
  "Standard Sit-ups",
  "Bicycle Crunches",
  "Russian Twists",
  "Leg Raises",
  "Flutter Kicks",
  "Standard Mountain Climbers",
  "Cross-Body Mountain Climbers",
  "Standard L-Sit",
  "Tucked L-Sit",
  "Standard Squats",
  "Sumo Squats",
  "Bulgarian Split Squats",
  "Pistol Squats",
  "Forward Lunges",
  "Reverse Lunges",
  "Walking Lunges",
  "Side Lunges",
  "Standing Leg Raises",
  "Donkey Kicks",
  "Standard Calf Raises",
  "Single-Leg Calf Raises",
  "Standard Burpees",
  "Half Burpees",
  "Bear Crawls",
  "Jumping Jacks",
  "Flat Bench Press ",
  "Incline Bench Press",
  "Decline Bench Press",
  "Dumbbell Flys",
  "Machine Flys",
  "Chest Press Machine",
  "Bent Over Rows",
  "Deadlifts",
  "Lat Pulldowns",
  "Seated Rows",
  "T-Bar Rows",
  "Barbell Shoulder Press",
  "Dumbell Shoulder Press",
  "Machine Shoulder Press",
  "Lateral Raises",
  "Front Raises",
  "Rear Delt Flys",
  "Shrugs",
  "Barbell Bicep Curls",
  "Dumbell Bicep Curls",
  "Machine Bicep Curls",
  "Skull Crushers Tricep Extensions",
  "Overhead Tricep Extensions",
  "Hammer Curls",
  "Preacher Curls",
  "Tricep Pushdowns",
  "Weighted Sit-ups/Crunches",
  "Cable Crunches",
  "Weighted Russian Twists",
  "Hanging Leg Raises",
  "Barbell Squats",
  "Dumbbell Squats",
  "Smith Machine Squats",
  "Leg Press",
  "Weighted Lunges",
  "Leg Curls",
  "Leg Extensions",
  "Seated Calf Raises",
  "Standing Calf Raises",
  "Clean and Jerk",
  "Snatch",
  "Kettlebell Swings",
  "Turkish Get-Up",
];
